# Generated by Django 6.0.2 on 2026-02-13 10:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('like', '0003_initial'),
        ('post', '0003_alter_post_author_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='user_id',
            new_name='author_id',
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('author_id', 'post_id')},
        ),
    ]
